const certifications = [
  {
    title: 'Frontend Developer (React)',
    description: 'Certified in React frontend.',
    icon: 'react',
    duration: '90 mins',
    passingScore: '70%',
  },
  {
    title: 'Software Engineer',
    description: 'Showcase your core skills.',
    icon: 'codeforces',
    duration: '120 mins',
    passingScore: '75%',
  },
  {
    title: 'Software Engineer Intern',
    description: 'Perfect for students and freshers.',
    icon: 'github',
    duration: '60 mins',
    passingScore: '65%',
  },
  {
    title: 'Angular (Basic)',
    description: 'Demonstrate Angular basics.',
    icon: 'angular',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'Angular (Intermediate)',
    description: 'Advanced Angular knowledge.',
    icon: 'angular',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'C# (Basic)',
    description: 'Core C# fundamentals test.',
    icon: 'csharp',
    duration: '70 mins',
    passingScore: '70%',
  },
  {
    title: 'CSS (Basic)',
    description: 'Showcase your styling skills with CSS.',
    icon: 'css3',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'Go (Basic)',
    description: 'Fundamentals of the Go language.',
    icon: 'go',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'JavaScript (Basic)',
    description: 'Basic JS certification test.',
    icon: 'javascript',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'Go (Intermediate)',
    description: 'Intermediate knowledge of Golang.',
    icon: 'go',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'Java (Basic)',
    description: 'Core Java programming certification.',
    icon: 'java',
    duration: '70 mins',
    passingScore: '70%',
  },
  {
    title: 'JavaScript (Intermediate)',
    description: 'Deep knowledge of JavaScript.',
    icon: 'javascript',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'Node (Basic)',
    description: 'Core concepts of Node.js.',
    icon: 'nodedotjs',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'Problem Solving (Basic)',
    description: 'Logical and analytical skill test.',
    icon: 'leetcode',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'Node.js (Intermediate)',
    description: 'Advanced server-side skills in Node.js.',
    icon: 'nodedotjs',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'Python (Basic)',
    description: 'Validate Python fundamentals.',
    icon: 'python',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'Problem Solving (Proficient)',
    description: 'Advanced problem-solving capability.',
    icon: 'hackerrank',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'R (Basic)',
    description: 'Get certified in basic R concepts.',
    icon: 'r',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'React (Basic)',
    description: 'Basic level React development test.',
    icon: 'react',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'R (Intermediate)',
    description: 'Advanced skills in R programming.',
    icon: 'r',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'Rest API (Intermediate)',
    description: 'Deep understanding of REST API systems.',
    icon: 'apachenetbeanside',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'SQL (Intermediate)',
    description: 'Database operations and relational queries.',
    icon: 'postgresql',
    duration: '90 mins',
    passingScore: '75%',
  },
  {
    title: 'SQL (Basic)',
    description: 'Fundamentals of databases and SQL.',
    icon: 'sqlite',
    duration: '60 mins',
    passingScore: '70%',
  },
  {
    title: 'SQL (Advanced)',
    description: 'Mastery in SQL querying and joins.',
    icon: 'mysql',
    duration: '120 mins',
    passingScore: '80%',
  },
];

export default certifications;
